#' Posterior-predictive CFA fit-index cutoffs under PCM unidimensionality
#'
#' Tests whether the observed one-factor categorical-CFA fit indices (CFI,
#' RMSEA, SRMR) are consistent with the data being generated by a
#' unidimensional Rasch / Partial Credit Model. The simulation generates
#' \code{iterations} datasets from the fitted PCM (or RM, for dichotomous
#' data) using the observed item parameters and a resampled person
#' distribution; each simulated dataset is fitted with
#' \code{lavaan::cfa(..., ordered = TRUE, estimator = "WLSMV")} and the
#' three fit indices are recorded. The result is a parametric-bootstrap
#' null distribution against which the observed CFA fit can be compared,
#' one-sided in the unfavourable direction for each index (CFI from
#' below; RMSEA and SRMR from above).
#'
#' At the default 99th-percentile cutoff, an item is flagged when the
#' observed value lies in the worst 1\% of the simulated null
#' distribution.
#'
#' @param data A data.frame or matrix of item responses (non-negative
#'   integers, 0-based). One column per item, one row per person.
#' @param iterations Integer. Number of parametric-bootstrap iterations.
#'   Default `250`.
#' @param percentile Numeric in (50, 100). The strictness of the
#'   one-sided cutoff. Default `99`. Higher = stricter:
#'   * For CFI (higher = better fit), the cutoff is the
#'     `(100 - percentile)`-th percentile of the simulated null
#'     distribution; observed values *below* this are flagged.
#'   * For RMSEA and SRMR (lower = better fit), the cutoff is the
#'     `percentile`-th percentile; observed values *above* this are
#'     flagged.
#' @param output Character. `"kable"` (default) returns a formatted
#'   `knitr::kable()` summary of observed values vs cutoffs, with the
#'   full result list attached as `attr(., "result")`. `"list"` returns
#'   the result list directly.
#' @param parallel Logical. If `TRUE` (default), uses parallel processing
#'   via `mirai`. Falls back to sequential if `mirai` is not installed or
#'   `n_cores` cannot be resolved.
#' @param n_cores Integer or `NULL`. Number of parallel workers. When
#'   `NULL`, `getOption("mc.cores")` is consulted; if neither is set,
#'   sequential is used.
#' @param verbose Logical. Show a progress bar (default `FALSE`).
#' @param seed Integer or `NULL`. Master seed for reproducibility.
#' @param estimator Character. The lavaan estimator passed to
#'   `lavaan::cfa()`. Default `"WLSMV"`. Other limited-information
#'   estimators that produce robust/scaled fit indices (e.g.,
#'   `"DWLS"`, `"ULSMV"`) are also accepted; full-information ML is
#'   rejected (incompatible with `ordered = TRUE`).
#'
#' @return If `output = "kable"`, a `knitr_kable` object summarising
#'   each index against its cutoff, with the full result list as
#'   `attr(., "result")`. If `output = "list"`, that list directly. The
#'   list has components:
#' \describe{
#'   \item{`observed`}{Named numeric vector of observed CFA fit indices
#'     (`cfi.scaled`, `rmsea.scaled`, `srmr`).}
#'   \item{`simulated`}{data.frame with one row per successful iteration
#'     and columns `iteration`, `cfi`, `rmsea`, `srmr`.}
#'   \item{`percentile`}{Numeric: the strictness setting used.}
#'   \item{`cutoffs`}{Named numeric vector (`cfi`, `rmsea`, `srmr`) of
#'     simulated cutoffs at the chosen percentile.}
#'   \item{`flagged`}{Named logical vector indicating whether each
#'     observed index falls outside its cutoff in the unfavourable
#'     direction.}
#'   \item{`actual_iterations`}{Number of successful MC iterations.}
#'   \item{`sample_n`}{Number of complete cases used.}
#'   \item{`n_items`}{Number of items.}
#'   \item{`item_names`}{Character vector of item names.}
#'   \item{`is_polytomous`}{Logical: was a PCM (vs RM) fitted?}
#'   \item{`estimator`}{The lavaan estimator used.}
#' }
#'
#' @details
#' \strong{Generative model.} The data-generating process for each
#' simulated dataset is the PCM (or RM) fitted to the observed data,
#' with persons drawn from the empirical theta distribution
#' (resampled with replacement). This means the simulated data perfectly
#' satisfy the PCM unidimensional assumption.
#'
#' \strong{Estimation model.} The CFA on each simulated dataset uses a
#' single-factor model with all items as ordinal indicators
#' (`F1 =~ I1 + I2 + ...`), fitted with `WLSMV` by default. Reported
#' CFI / RMSEA are the Satorra-Bentler-scaled variants (`cfi.scaled`,
#' `rmsea.scaled`) for consistency across iterations; the Yuan-Bentler
#' mean-variance-adjusted "robust" variants are sometimes `NA` at small
#' n and would produce holes in the simulated null distribution. SRMR
#' is reported unchanged. For percentile-based comparison the binding
#' requirement is that the same metric is computed for observed and
#' simulated iterations, which both variants satisfy.
#'
#' \strong{Why a null distribution.} A perfectly PCM-unidimensional
#' dataset will typically not yield CFA fit indices at their ideal
#' values (CFI = 1, RMSEA = 0). Two reasons: (1) PCM uses a logistic
#' threshold structure while WLSMV uses a probit-link via the
#' polychoric correlation matrix, so there is a small built-in metric
#' mismatch even under correct unidimensionality; (2) finite samples
#' produce sampling variability in the polychoric correlations. The
#' simulated distribution captures both. Comparing observed to this
#' distribution is more honest than rule-of-thumb cutoffs (CFI > 0.95,
#' RMSEA < 0.06, SRMR < 0.08) which were derived under continuous-data
#' ML and do not transfer cleanly to ordinal WLSMV.
#'
#' \strong{Iteration failures.} Some simulated datasets cause WLSMV to
#' fail (non-positive-definite polychoric matrix, boundary thresholds,
#' empty categories). Failed iterations are recorded with a character
#' message and dropped; `actual_iterations` reflects the number that
#' succeeded.
#'
#' \strong{Companion functions.} See \code{\link{RMdimCFAPlot}} for a
#' faceted visualisation of the observed value against each simulated
#' distribution. This test complements \code{\link{RMdimResidualPCA}} (which
#' identifies *which* items deviate) and \code{\link{RMdimMartinLof}} (which
#' tests a specific hypothesised partition).
#'
#' @references
#' Yuan, K.-H., & Bentler, P. M. (2000). Three likelihood-based methods
#' for mean and covariance structure analysis with nonnormal missing
#' data. \emph{Sociological Methodology, 30}(1), 165-200.
#' \doi{10.1111/0081-1750.00078}
#'
#' Rosseel, Y. (2012). lavaan: An R Package for Structural Equation
#' Modeling. \emph{Journal of Statistical Software, 48}(2), 1-36.
#' \doi{10.18637/jss.v048.i02}
#'
#' @seealso \code{\link{RMdimCFAPlot}}, \code{\link{RMdimResidualPCA}},
#'   \code{\link{RMdimMartinLof}}
#'
#' @examples
#' \donttest{
#' data("raschdat1", package = "eRm")
#' RMdimCFACutoff(raschdat1[, 1:8], iterations = 50,
#'             parallel = FALSE, seed = 1)
#' }
#' \dontrun{
#' # Default 250 iterations with parallel processing
#' result <- RMdimCFACutoff(raschdat1[, 1:8], n_cores = 4, seed = 1)
#' result$observed
#' result$flagged
#' RMdimCFAPlot(result)
#' }
#'
#' @importFrom rlang .data
#' @export
RMdimCFACutoff <- function(data,
                        iterations = 250L,
                        percentile = 99,
                        output     = c("kable", "list"),
                        parallel   = TRUE,
                        n_cores    = NULL,
                        verbose    = FALSE,
                        seed       = NULL,
                        estimator  = "WLSMV") {

  output <- match.arg(output)

  if (!requireNamespace("lavaan", quietly = TRUE)) {
    stop("Package 'lavaan' is required for RMdimCFACutoff(). ",
         "Install with: install.packages(\"lavaan\")",
         call. = FALSE)
  }
  if (output == "kable" && !requireNamespace("knitr", quietly = TRUE)) {
    stop("Package 'knitr' is required for output = \"kable\".",
         call. = FALSE)
  }

  if (!is.numeric(percentile) || length(percentile) != 1L ||
      !is.finite(percentile) || percentile <= 50 || percentile >= 100) {
    stop("`percentile` must be a single numeric in (50, 100). ",
         "Common choices: 95, 99, 99.5.", call. = FALSE)
  }

  estimator <- toupper(estimator[1L])
  if (estimator %in% c("ML", "MLR", "MLM", "MLF")) {
    stop("`estimator = \"", estimator, "\"` is not appropriate for ",
         "ordinal-CFA. Use a limited-information estimator such as ",
         "\"WLSMV\", \"DWLS\", or \"ULSMV\".", call. = FALSE)
  }

  validate_response_data(data)

  # rgl workaround
  old_rgl <- getOption("rgl.useNULL")
  options(rgl.useNULL = TRUE)
  on.exit(options(rgl.useNULL = old_rgl), add = TRUE)

  data <- stats::na.omit(as.data.frame(data))
  if (nrow(data) == 0L) {
    stop("No complete cases in `data`.", call. = FALSE)
  }
  if (ncol(data) < 3L) {
    stop("RMdimCFACutoff() requires at least 3 items for a one-factor CFA.",
         call. = FALSE)
  }

  # Parallel setup -- mirrors RMdimResidualPCACutoff()
  use_parallel <- parallel && requireNamespace("mirai", quietly = TRUE)
  if (parallel && !use_parallel) {
    message("Install 'mirai' for parallel processing: install.packages(\"mirai\")")
    message("Running sequentially...")
  }
  if (use_parallel) {
    if (is.null(n_cores)) n_cores <- getOption("mc.cores")
    if (is.null(n_cores)) {
      warning(
        "For parallel processing, specify n_cores or set options(mc.cores = N).\n",
        "Falling back to sequential.",
        call. = FALSE
      )
      use_parallel <- FALSE
    } else {
      n_cores <- min(n_cores, iterations)
    }
  }

  if (!is.null(seed)) set.seed(seed)
  sim_seeds <- sample.int(.Machine$integer.max, iterations)

  data_mat       <- as.matrix(data)
  sample_n       <- nrow(data_mat)
  is_polytomous  <- max(data_mat, na.rm = TRUE) > 1L
  item_names_vec <- colnames(data_mat)
  if (is.null(item_names_vec))
    item_names_vec <- paste0("V", seq_len(ncol(data_mat)))

  # Fit observed Rasch / PCM and assemble simulation list
  if (is_polytomous) {
    pcm_fit     <- eRm::PCM(data_mat)
    pp          <- eRm::person.parameter(pcm_fit)
    theta_table <- pp$theta.table[["Person Parameter"]]
    raw_scores  <- rowSums(data_mat, na.rm = TRUE)
    thetas      <- as.numeric(stats::na.omit(theta_table[raw_scores]))
    thresh_mat  <- extract_item_thresholds(data_mat)
    deltaslist  <- lapply(seq_len(nrow(thresh_mat)), function(i) {
      as.numeric(thresh_mat[i, !is.na(thresh_mat[i, ])])
    })
    sim_data_list <- list(
      type       = "polytomous",
      thetas     = thetas,
      deltaslist = deltaslist,
      n_items    = ncol(data_mat),
      sample_n   = sample_n,
      item_names = item_names_vec,
      estimator  = estimator
    )
  } else {
    rm_fit      <- eRm::RM(data_mat)
    pp          <- eRm::person.parameter(rm_fit)
    theta_table <- pp$theta.table[["Person Parameter"]]
    raw_scores  <- rowSums(data_mat, na.rm = TRUE)
    thetas      <- as.numeric(stats::na.omit(theta_table[raw_scores]))
    item_params <- -rm_fit$betapar
    sim_data_list <- list(
      type        = "dichotomous",
      thetas      = thetas,
      item_params = item_params,
      n_items     = ncol(data_mat),
      sample_n    = sample_n,
      item_names  = item_names_vec,
      estimator   = estimator
    )
  }

  # Observed CFA fit on the actual data
  observed_fit <- run_single_cfa_sim(
    seed      = NA,             # seed unused for observed
    data_list = sim_data_list,
    obs_data  = as.data.frame(data_mat)
  )
  if (!is.numeric(observed_fit)) {
    stop("Observed CFA fit failed: ", observed_fit, call. = FALSE)
  }
  names(observed_fit) <- c("cfi", "rmsea", "srmr")

  # Run the simulation
  if (use_parallel) {
    results_raw <- run_cfa_sim_parallel(iterations, sim_seeds,
                                        sim_data_list, n_cores, verbose)
  } else {
    results_raw <- run_cfa_sim_sequential(iterations, sim_seeds,
                                          sim_data_list, verbose)
  }

  ok         <- vapply(results_raw, is.numeric, logical(1L))
  successful <- results_raw[ok]

  if (length(successful) == 0L) {
    failed_msgs <- unlist(results_raw[!ok])
    sample_msg <- if (length(failed_msgs) > 0L) {
      unique(failed_msgs)[1L]
    } else {
      "(no message captured)"
    }
    stop("All CFA simulation iterations failed. Example: ", sample_msg,
         call. = FALSE)
  }

  actual_iterations <- length(successful)
  sim_mat <- do.call(rbind, successful)
  colnames(sim_mat) <- c("cfi", "rmsea", "srmr")

  simulated_df <- data.frame(
    iteration = seq_len(actual_iterations),
    cfi       = as.numeric(sim_mat[, "cfi"]),
    rmsea     = as.numeric(sim_mat[, "rmsea"]),
    srmr      = as.numeric(sim_mat[, "srmr"]),
    stringsAsFactors = FALSE
  )

  # One-sided cutoffs at the chosen percentile.
  # CFI: lower = worse, so cutoff = (100 - percentile)th percentile.
  # RMSEA / SRMR: higher = worse, cutoff = percentile-th percentile.
  cutoffs <- compute_cfa_cutoffs(simulated_df, percentile)
  flagged <- compute_cfa_flagged(observed_fit, cutoffs)

  result <- list(
    observed          = observed_fit,
    simulated         = simulated_df,
    percentile        = percentile,
    cutoffs           = cutoffs,
    flagged           = flagged,
    actual_iterations = actual_iterations,
    sample_n          = sample_n,
    n_items           = ncol(data_mat),
    item_names        = item_names_vec,
    is_polytomous     = is_polytomous,
    estimator         = estimator
  )

  if (output == "list") return(result)

  # output == "kable"
  kbl <- render_cfa_kable(result)
  attr(kbl, "result") <- result
  kbl
}

#' Compute one-sided CFA-fit cutoffs at the given percentile
#'
#' @keywords internal
#' @noRd
compute_cfa_cutoffs <- function(simulated_df, percentile) {
  pct <- percentile / 100
  # Filter to finite values -- lavaan can return Inf for RMSEA when
  # chi-square is exactly 0 (degenerate near-perfect fit on a
  # simulated dataset), which would otherwise propagate into the cutoff.
  cfi_v   <- simulated_df$cfi[is.finite(simulated_df$cfi)]
  rmsea_v <- simulated_df$rmsea[is.finite(simulated_df$rmsea)]
  srmr_v  <- simulated_df$srmr[is.finite(simulated_df$srmr)]
  c(
    cfi   = as.numeric(stats::quantile(cfi_v,   1 - pct, na.rm = TRUE)),
    rmsea = as.numeric(stats::quantile(rmsea_v, pct,     na.rm = TRUE)),
    srmr  = as.numeric(stats::quantile(srmr_v,  pct,     na.rm = TRUE))
  )
}

#' Tiny ordinal-suffix helper for percentile labels (1st, 2nd, 3rd, 99th)
#'
#' @keywords internal
#' @noRd
ordinal_suffix <- function(n) {
  n_int <- as.integer(round(n))
  if (n_int %% 100 %in% c(11L, 12L, 13L)) return("th")
  switch(as.character(n_int %% 10),
         "1" = "st", "2" = "nd", "3" = "rd", "th")
}

#' Apply directional flagging given observed values + cutoffs
#'
#' @keywords internal
#' @noRd
compute_cfa_flagged <- function(observed, cutoffs) {
  c(
    cfi   = !is.na(observed[["cfi"]])   && observed[["cfi"]]   < cutoffs[["cfi"]],
    rmsea = !is.na(observed[["rmsea"]]) && observed[["rmsea"]] > cutoffs[["rmsea"]],
    srmr  = !is.na(observed[["srmr"]])  && observed[["srmr"]]  > cutoffs[["srmr"]]
  )
}

#' Render the observed-vs-cutoff summary as a kable
#'
#' @keywords internal
#' @noRd
render_cfa_kable <- function(result) {
  pct_label   <- result$percentile
  cfi_pct_lbl <- 100 - pct_label
  pct_suffix  <- ordinal_suffix(pct_label)
  cfi_suffix  <- ordinal_suffix(cfi_pct_lbl)

  df <- data.frame(
    Index     = c("CFI", "RMSEA", "SRMR"),
    Observed  = round(c(result$observed[["cfi"]],
                        result$observed[["rmsea"]],
                        result$observed[["srmr"]]), 4),
    Cutoff    = round(c(result$cutoffs[["cfi"]],
                        result$cutoffs[["rmsea"]],
                        result$cutoffs[["srmr"]]), 4),
    Direction = c(paste0("< ", cfi_pct_lbl, cfi_suffix, " pct"),
                  paste0("> ", pct_label,   pct_suffix, " pct"),
                  paste0("> ", pct_label,   pct_suffix, " pct")),
    Flagged   = ifelse(result$flagged[c("cfi", "rmsea", "srmr")],
                       "TRUE", ""),
    stringsAsFactors = FALSE
  )

  caption <- paste0(
    if (result$is_polytomous) "Partial Credit Model" else "Rasch Model",
    " posterior-predictive CFA fit-index check. ",
    "Observed CFA fit (one-factor, lavaan ", result$estimator,
    ", ordered = TRUE) vs simulated null distribution under ",
    if (result$is_polytomous) "PCM" else "RM",
    " unidimensionality. n = ", result$sample_n,
    " complete cases, ", result$n_items, " items, ",
    result$actual_iterations, " parametric-bootstrap iterations. ",
    "Cutoffs are one-sided at the ", pct_label,
    "th percentile of the simulated distribution; an item is flagged ",
    "when the observed value lies in the worst ",
    100 - pct_label,
    "% of the null distribution in the unfavourable direction."
  )

  knitr::kable(df, format = "pipe", caption = caption,
               row.names = FALSE)
}

# ===========================================================================
# Plot companion
# ===========================================================================

#' Plot observed CFA fit indices against the simulated null distribution
#'
#' Faceted histograms of the simulated CFI, RMSEA, and SRMR distributions
#' (one panel per index), with the observed value overlaid as a vertical
#' line. The line is coloured red when the observed value falls outside
#' the chosen percentile of the simulation in the unfavourable direction
#' (CFI from below; RMSEA / SRMR from above), and grey otherwise.
#'
#' @param cutoff_res The list returned by \code{\link{RMdimCFACutoff}} with
#'   `output = "list"`, or the kable returned with `output = "kable"`
#'   (the underlying list is read from `attr(., "result")`).
#' @param percentile Numeric in (50, 100) or `NULL`. When supplied, the
#'   cutoff and the flagged status are recomputed at this percentile
#'   from the simulated distribution stored in `cutoff_res` (no
#'   re-simulation needed). When `NULL` (default), the percentile that
#'   was used by the original `RMdimCFACutoff()` call is reused.
#'
#' @return A `ggplot` object.
#'
#' @seealso \code{\link{RMdimCFACutoff}}
#'
#' @examples
#' \donttest{
#' data("raschdat1", package = "eRm")
#' res <- RMdimCFACutoff(raschdat1[, 1:8], iterations = 50,
#'                    parallel = FALSE, seed = 1, output = "list")
#' RMdimCFAPlot(res)                 # use the percentile from RMdimCFACutoff()
#' RMdimCFAPlot(res, percentile = 95) # override (no re-simulation needed)
#' }
#'
#' @importFrom rlang .data
#' @export
RMdimCFAPlot <- function(cutoff_res, percentile = NULL) {

  if (!requireNamespace("ggplot2", quietly = TRUE)) {
    stop("Package 'ggplot2' is required for RMdimCFAPlot(). ",
         "Install with: install.packages(\"ggplot2\")",
         call. = FALSE)
  }

  # Accept either a kable (with attr "result") or the raw list
  if (inherits(cutoff_res, "knitr_kable")) {
    cutoff_res <- attr(cutoff_res, "result")
  }
  if (!is.list(cutoff_res) ||
      !all(c("observed", "simulated", "percentile", "cutoffs", "flagged") %in%
           names(cutoff_res))) {
    stop("`cutoff_res` must be the result returned by RMdimCFACutoff().",
         call. = FALSE)
  }

  if (is.null(percentile)) {
    percentile <- cutoff_res$percentile
  } else {
    if (!is.numeric(percentile) || length(percentile) != 1L ||
        !is.finite(percentile) || percentile <= 50 || percentile >= 100) {
      stop("`percentile` must be a single numeric in (50, 100), or NULL.",
           call. = FALSE)
    }
    cutoff_res$cutoffs <- compute_cfa_cutoffs(cutoff_res$simulated,
                                              percentile)
    cutoff_res$flagged <- compute_cfa_flagged(cutoff_res$observed,
                                              cutoff_res$cutoffs)
  }

  # Long-format data for faceting
  sim_long <- data.frame(
    Index = factor(rep(c("CFI", "RMSEA", "SRMR"),
                       each = nrow(cutoff_res$simulated)),
                   levels = c("CFI", "RMSEA", "SRMR")),
    Value = c(cutoff_res$simulated$cfi,
              cutoff_res$simulated$rmsea,
              cutoff_res$simulated$srmr),
    stringsAsFactors = FALSE
  )

  obs_df <- data.frame(
    Index    = factor(c("CFI", "RMSEA", "SRMR"),
                      levels = c("CFI", "RMSEA", "SRMR")),
    Observed = c(cutoff_res$observed[["cfi"]],
                 cutoff_res$observed[["rmsea"]],
                 cutoff_res$observed[["srmr"]]),
    Cutoff   = c(cutoff_res$cutoffs[["cfi"]],
                 cutoff_res$cutoffs[["rmsea"]],
                 cutoff_res$cutoffs[["srmr"]]),
    Flagged  = c(cutoff_res$flagged[["cfi"]],
                 cutoff_res$flagged[["rmsea"]],
                 cutoff_res$flagged[["srmr"]]),
    stringsAsFactors = FALSE
  )
  obs_df$Color <- ifelse(obs_df$Flagged, "red", "grey30")

  cfi_pct_lbl <- 100 - percentile
  caption <- paste0(
    "Histograms: ", cutoff_res$actual_iterations,
    " parametric-bootstrap datasets simulated under ",
    if (cutoff_res$is_polytomous) "PCM" else "RM",
    " unidimensionality at n = ", cutoff_res$sample_n,
    ",\nrefitted with lavaan::cfa(ordered = TRUE, estimator = \"",
    cutoff_res$estimator, "\").\n",
    "Diamond: observed value (red = flagged at the ", percentile,
    "th percentile in the unfavourable direction).\n",
    "Dashed line: cutoff (CFI: ", cfi_pct_lbl,
    "th pct; RMSEA / SRMR: ", percentile, "th pct)."
  )

  #caption <- paste(strwrap(caption, width = 90), collapse = "\n")

  ggplot2::ggplot(sim_long,
                  ggplot2::aes(x = .data$Value)) +
    ggplot2::geom_histogram(bins = 30, fill = "grey80",
                            colour = "white") +
    ggplot2::geom_vline(
      data = obs_df,
      ggplot2::aes(xintercept = .data$Cutoff),
      linetype = "dashed", colour = "grey40"
    ) +
    ggplot2::geom_point(
      data = obs_df,
      ggplot2::aes(x = .data$Observed, colour = .data$Color), y = 0,
      size = 4.5, shape = 18
    ) +
    ggplot2::scale_colour_identity() +
    ggplot2::facet_wrap(~ Index, scales = "free", nrow = 1) +
    ggplot2::labs(
      title   = "Observed CFA fit vs simulated null distribution",
      x       = "Fit index value",
      y       = "Count of simulated datasets",
      caption = caption
    ) +
    ggplot2::theme_bw(base_size = 13) +
    ggplot2::theme(
      plot.caption = ggplot2::element_text(hjust = 0, face = "italic", size = 9)
    ) +
    er2_axis_margins()
}

# ===========================================================================
# Internal: single iteration
# ===========================================================================

#' Run one CFA-fit-index simulation iteration
#'
#' If `obs_data` is supplied, it is used directly (i.e., this is the
#' observed-fit call); otherwise a new dataset is simulated under the
#' fitted PCM/RM. Returns a length-3 numeric vector `(cfi, rmsea, srmr)`
#' on success, or a character message on failure.
#'
#' @keywords internal
#' @noRd
run_single_cfa_sim <- function(seed, data_list, obs_data = NULL) {

  build_sim_df <- function() {
    set.seed(seed)
    thetas_res <- sample(data_list$thetas, size = data_list$sample_n,
                         replace = TRUE)

    if (data_list$type == "dichotomous") {
      sim_mat <- psychotools::rrm(theta = thetas_res,
                                  beta  = data_list$item_params)
      sim_df <- as.data.frame(sim_mat$data)
      colnames(sim_df) <- data_list$item_names

      # WLSMV needs at least 2 observations in each category to compute
      # the polychoric correlation matrix; values much below ~5 produce
      # unstable thresholds. We use a relaxed threshold of 2 (vs the
      # tighter cap used by run_single_pca_sim) because CFA does not
      # require the same level of variability that eRm::RM does.
      pos_counts <- colSums(sim_df, na.rm = TRUE)
      neg_counts <- nrow(sim_df) - pos_counts
      if (any(pos_counts < 2L) || any(neg_counts < 2L)) {
        return("validation_failed: an item has < 2 responses in one of the two categories")
      }
      return(sim_df)
    }

    sim_mat <- sim_partial_score(data_list$deltaslist, thetas_res)
    sim_df  <- as.data.frame(sim_mat)
    colnames(sim_df) <- data_list$item_names

    n_cats <- vapply(data_list$deltaslist,
                     function(d) length(d) + 1L, integer(1L))
    for (j in seq_len(ncol(sim_df))) {
      tab <- tabulate(sim_df[[j]] + 1L, nbins = n_cats[j])
      if (any(tab == 0L)) {
        return("validation_failed: not all categories represented")
      }
    }
    sim_df
  }

  tryCatch({
    fit_df <- if (is.null(obs_data)) build_sim_df() else obs_data
    if (is.character(fit_df)) return(fit_df)

    fmla <- paste0("F1 =~ ",
                   paste(data_list$item_names, collapse = " + "))

    # Pass warn = FALSE to lavaan to suppress its post-fit "negative ov
    # variances" messages, plus suppressWarnings/suppressMessages around
    # the call to mop up anything emitted via warning()/message().
    fit <- suppressWarnings(suppressMessages(
      lavaan::cfa(
        model     = fmla,
        data      = fit_df,
        ordered   = data_list$item_names,
        estimator = data_list$estimator,
        warn      = FALSE,
        verbose   = FALSE
      )
    ))

    if (!isTRUE(lavaan::lavInspect(fit, "converged"))) {
      return("convergence_failed: lavaan did not converge")
    }

    suppressWarnings(extract_cfa_fit(fit, data_list$estimator))
  }, error = function(e) as.character(conditionMessage(e)))
}

#' Pull (CFI, RMSEA, SRMR) from a fitted lavaan object
#'
#' Uses the Satorra-Bentler-SCALED CFI / RMSEA variants when available
#' (`cfi.scaled`, `rmsea.scaled`), falling back to the uncorrected
#' `cfi` / `rmsea` when not.
#'
#' Why scaled rather than the Yuan-Bentler "robust" variants that
#' `WLSMV` is named after: the `.robust` (mean-variance-adjusted)
#' variants return `NA` for a non-trivial fraction of fits at small
#' n (when chi-square is near zero), which produces holes in the
#' simulated null distribution. The `.scaled` (Satorra-Bentler)
#' variants are well-defined across nearly all fits, and for a
#' parametric-bootstrap percentile comparison the binding requirement
#' is that the same metric is computed for observed and simulated
#' iterations -- which version of the chi-square correction is used
#' matters less than internal consistency. SRMR is unaffected by either
#' correction.
#'
#' The `estimator` argument is kept for signature compatibility but is
#' unused -- we ask lavaan directly so the function works for any
#' estimator that produces these variants.
#'
#' @keywords internal
#' @noRd
extract_cfa_fit <- function(fit, estimator = NULL) {
  fm <- lavaan::fitMeasures(fit)
  pick_scaled <- function(name) {
    key_s <- paste0(name, ".scaled")
    if (key_s %in% names(fm) && is.finite(fm[[key_s]])) {
      return(as.numeric(fm[[key_s]]))
    }
    if (name %in% names(fm) && is.finite(fm[[name]])) {
      return(as.numeric(fm[[name]]))
    }
    NA_real_
  }
  c(pick_scaled("cfi"),
    pick_scaled("rmsea"),
    as.numeric(fm[["srmr"]]))
}

# ===========================================================================
# Internal: parallel runner
# ===========================================================================

#' @keywords internal
#' @noRd
run_cfa_sim_parallel <- function(iterations, sim_seeds, sim_data_list,
                                 n_cores, verbose = FALSE) {
  mirai::daemons(n_cores)
  on.exit(mirai::daemons(0), add = TRUE)

  if (verbose) {
    message(sprintf("Starting %d daemons...", n_cores))
    pb <- utils::txtProgressBar(min = 0, max = iterations, style = 3)
  }

  tasks <- lapply(seq_len(iterations), function(i) {
    mirai::mirai(
      { run_single_cfa_sim(seed, data_list) },
      seed                = sim_seeds[i],
      data_list           = sim_data_list,
      run_single_cfa_sim  = run_single_cfa_sim,
      extract_cfa_fit     = extract_cfa_fit,
      sim_partial_score   = sim_partial_score,
      sim_poly_item       = sim_poly_item
    )
  })

  results <- vector("list", iterations)
  for (i in seq_len(iterations)) {
    res <- mirai::call_mirai(tasks[[i]])$data
    results[[i]] <- if (inherits(res, "errorValue")) "mirai_error" else res
    if (verbose) utils::setTxtProgressBar(pb, i)
  }

  if (verbose) {
    close(pb)
    message("")
  }

  results
}

# ===========================================================================
# Internal: sequential runner
# ===========================================================================

#' @keywords internal
#' @noRd
run_cfa_sim_sequential <- function(iterations, sim_seeds, sim_data_list,
                                   verbose = FALSE) {
  if (verbose) pb <- utils::txtProgressBar(min = 0, max = iterations, style = 3)

  results <- vector("list", iterations)
  for (i in seq_len(iterations)) {
    results[[i]] <- run_single_cfa_sim(sim_seeds[i], sim_data_list)
    if (verbose) utils::setTxtProgressBar(pb, i)
  }

  if (verbose) {
    close(pb)
    message("")
  }

  results
}
